services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
        - ./app:/app
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
        - db
  db:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis:
    image: redis:6.2.6-alpine
    hostname: redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker -l info
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
        - ./app:/app
    links:
      - redis
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
        - ./app:/app
    links:
      - redis
    ports:
      - "5555:5555"
    depends_on:
      - redis
